app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app_ParcelOrder:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\ParcelOrderController'
    name_prefix: api_1_ #naming collision 
